global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: quarkus-micrometer
    metrics_path: /api/q/metrics
    scrape_interval: 3s
    static_configs:
      - targets:
        - card-app:8080